//웹뷰로부터 요청 받을때 액션
type ReceiveActionProps = 'TEST' | 'REQUEST_PERMISSION' | 'FCM_TOKEN' | 'CURRENT_POSITION' | 'START_WATCH_POSITION' | 'STOP_WATCH_POSITION';

//웹뷰로 응답 보낼때 액션
type PostActionProps = 'TEST' | 'SEND_PERMISSION_STATUS' | 'SEND_FCM_TOKEN' | 'SEND_BACKGROUND_NOTIFICATION' | 'SEND_FOREGROUND_NOTIFICATION' | 'SEND_CURRENT_POSITION' | 'SEND_WATCH_POSITION';
